#!/bin/zsh

mkdir -p ./tmp
/bin/cp src/index.html tmp/
/bin/cp src/**/*.css tmp/
./node_modules/.bin/browserify src/index.js -o tmp/app.js


mkdir -p ./dist
/bin/cp ./tmp/index.html ./dist/
cat ./tmp/*.css > ./dist/app.css
local gmlk=$GOOGLE_MAPS_APA_DEV
if [[ $1 == "-p" ]]; then
    gmlk=$GOOGLE_MAPS_APA_PROD
    echo 'apa.brycekbargar.com' > ./dist/CNAME
fi
sed -e "s/GOOGLE_MAPS_LOADER_KEY/$gmlk/" ./tmp/app.js > ./dist/app.js

