#!/bin/zsh

mkdir -p ./build
./node_modules/.bin/browserify src/index.js -o build/app.js
/bin/cp src/index.html build/
/bin/cp src/**/*.css build/

mkdir -p ./dist
/bin/cp ./build/index.html ./dist/
sed -e "s/GOOGLE_MAPS_LOADER_KEY/$GOOGLE_MAPS_LOADER_KEY/" ./build/app.js > ./dist/app.js
cat ./build/*.css > ./dist/app.css

